name: Build and Deploy Application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency: production_environment

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: volta-cli/action@v4

    - name: Compile CSS and JavaScript
      run: |
        npm install
        npm run production

    - name: Configure PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: 7.4
        extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml

    - name: Composer install
      run: |
        composer install --no-dev --no-interaction --prefer-dist
      
    - name: Download `deployer.phar`
      run: composer global require deployer/deployer:^7.3.1 --no-interaction --verbose --ansi

    - name: Get composer global bin-dir path
      id: composer-bin-dir
      run: echo "path=$(composer global config bin-dir --absolute)" >> $GITHUB_OUTPUT

    - name: Deploy
      uses: deployphp/action@v1
      with:
        deployer-binary: ${{ steps.composer-bin-dir.outputs.path }}/dep
        private-key: ${{ secrets.PRIVATE_KEY }}
        dep: 'deploy 206.189.200.129'

    - name: Copy Build Artifact
      run: |
        scp public/mix-manifest.json aaron@206.189.200.129:/var/www/budgeteer.aaroneisenberg.me/current/public/mix-manifest.json
        scp -pr public/js/ aaron@206.189.200.129:/var/www/budgeteer.aaroneisenberg.me/current/public/js/
        scp -pr public/css/ aaron@206.189.200.129:/var/www/budgeteer.aaroneisenberg.me/current/public/css/

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md
    #
    # - name: Run test suite
    #   run: composer run-script test
    # - name: Upload Build Files
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: npm-build
    #     path: |
    #       public/js/app.js
    #       public/css/app.css
    #       public/mix-manifest.json
    #
    # - name: Download and Publish Build Artifacts
    # - uses: actions/download-artifact@v3
    #     with:
    #       name: npm-build
