name: Build and Deploy Application

on:
  pull_request:
    types: [ closed ]
    branches: [ master ]

concurrency: production_environment

jobs:
  deploy:
    name: Deploy
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: volta-cli/action@v4

    - name: Compile CSS and JavaScript
      run: |
        cp .env.example .env
        npm install
        npm run production

    - name: Configure PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: 7.4
        extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml

    - name: Composer install
      run: |
        composer install --no-dev --no-interaction --prefer-dist
      
    - name: Download `deployer.phar`
      run: composer global require deployer/deployer:^7.3.1 --no-interaction --verbose --ansi

    - name: Get composer global bin-dir path
      id: composer-bin-dir
      run: echo "path=$(composer global config bin-dir --absolute)" >> $GITHUB_OUTPUT

    - name: Deploy
      uses: deployphp/action@v1
      with:
        deployer-binary: ${{ steps.composer-bin-dir.outputs.path }}/dep
        private-key: ${{ secrets.PRIVATE_KEY }}
        dep: 'deploy 206.189.200.129'

    - name: Copy Build Artifact
      run: |
        scp public/build/manifest.json aaron@206.189.200.129:/var/www/budgeteer.aaroneisenberg.me/current/public/build/manifest.json
        scp -pr public/build/assets/app.js aaron@206.189.200.129:/var/www/budgeteer.aaroneisenberg.me/current/public/build/assets/app.js
        scp -pr public/build/assets/app.css aaron@206.189.200.129:/var/www/budgeteer.aaroneisenberg.me/current/public/build/assets/app.css
