name: Build and Deploy Application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency: production_environment

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Compile CSS and JavaScript
      run: |
        npm install
        npm run prod

    - name: Configure PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: 7.4
        extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml

    - name: Composer install
      run: |
        composer install --no-dev --no-interaction --prefer-dist
      
    - name: Deploy
      uses: deployphp/action@v1
      with:
        private-key: ${{ secrets.PRIVATE_KEY }}
        dep: deploy 206.189.200.129

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
